all:
  file:
    - file "$file"
  mime-type:
    - file --mime-type "$file"
  # strings:  
  #   - strings "$file"
  # binwalk:
  #   - binwalk "$file"
mime-types:
  image:
    - exif
  # - repair
  audio:
    - echo audio
  video:
    - echo video
extensions:
  .pcap:
    - networkminer
    - networkminer
    - dlmkf
    - aaa
    - networkminer
    - b
  .apk:
    - unpack-apk  

packages:
  - find-outdated
pwn:
  - checksec
  - dogbolt-main
  - get-template
crypto:
  - export2john
  - detect-crypto
  - xorsearch
unknown:
  - virustotal
