all:
  file:
    - file "$file"
  mime-type:
    - file --mime-type "$file"
  # strings:  
  #   - strings "$file"
  # binwalk:
  #   - binwalk "$file"
image:
  - exif
  - repair
pcap:
  - networkminer
apk:
  - unpack-apk
packages:
  - find-outdated
pwn:
  - checksec
  - dogbolt-main
  - get-template
crypto:
  - export2john
  - detect-crypto
  - xorsearch
unknown:
  - virustotal
