all:
  file:
    - file "$file"
  mime-type:
    - file --mime-type "$file"
  # strings:  
  #   - strings "$file"
  # binwalk:
  #   - binwalk "$file"
mime-types:
  image:
    - exif
  # - repair
extensions:
  pcap:
    - networkminer
  apk:
    - unpack-apk  

packages:
  - find-outdated
pwn:
  - checksec
  - dogbolt-main
  - get-template
crypto:
  - export2john
  - detect-crypto
  - xorsearch
unknown:
  - virustotal
