all:
  file:
    - file -b "$file"
  mime-type:
    - file -b --mime-type "$file"
  # strings:  
  #   - strings "$file"
  # binwalk:
  #   - binwalk "$file"
mime-types:
# contents for text files should come in preview
  image:
    exif:
    - exiftool "$file"
  # - repair
  audio:
    card:
      - echo audio
  video:
    card:
      - echo video
  image/gif:
    card:
      - echo doesitwork
    card2:
      - echo bdoesitwork
extensions:
  .pcap:
    networkminer:
      - echo networkminer
  .apk:
    unpacked:
      - echo unpack-apk  

packages:
  - find-outdated
pwn:
  - checksec
  - dogbolt-main
  - get-template
crypto:
  - export2john
  - detect-crypto
  - xorsearch
unknown:
  - virustotal
