all:
  file:
    - file -b "$file"
  mime-type:
    - file -b --mime-type "$file"
  # strings:  
  #   - strings "$file"
  # binwalk:
  #   - binwalk "$file"
mime-types:
# contents for text files should come in preview
  image:
    exif:
    - exiftool "$file"
  # - repair
  audio:
    audio:
      - echo audio
  video:
    video:
      - echo video
  image/gif:
    gif:
      - echo gif
extensions:
  .pcap:
    networkminer:
      - echo networkminer
  .apk:
    unpacked:
      - echo unpack-apk  
filenames:
  requirements.txt:
    python modules:
      - echo python modules
  package.json:
    node modules:
      - echo node modules

# packages:
#   - find-outdated
# pwn:
#   - checksec
#   - dogbolt-main
#   - get-template
# crypto:
#   - export2john
#   - detect-crypto
#   - xorsearch
# unknown:
#   - virustotal
